### ISSUE TITLE
We should define the full specs of the deserialization with inheritance

### ISSUE THREAD

**Issue by noemi-salaun** [kaiu-io/serializer#8]
Before going further in the implementation with the risk of having to replace everything if we encounter a new unforeseen case, I think we should set the full specs of the deserialization with inheritance.

This issue should list all cases and how to manage them. This comment will be edited with the latest updates.

- Object without its discriminator field
- Object with unmatching discriminator value
- Register with children that does not extends the parent
- Register with the parent among the children
- Inheritance with implicit matching for the parent itself
- Recursive inheritance, with multiple levels, like grandchildren and further
- Register with the same classe multiple time for different discriminator value
- Register for different classes but the same discriminator value

<details>
<summary>Edit 2017-24-07</summary>

- Remove `Inheritance with explicit matching for the parent itself (same as above?)` because it's the same as registering the parent
- Add the case for multiple registration of the same classe, or the same disciminatorValue

</details>

**Comment by Supamiu** [comment]
I'll try to describe my own thoughts about each case:

>Object without its discriminator field
Either `return parent` if `allowSelf` is defined or `throw new TypeError(...)`, it allows more flexibility in API models, but we could add a warning to say something like "undefined value found in discriminator field ...".

>Object with unmatching discriminator value
I think we should act like this:

 - if parent has `allowSelf`, `return parent`.
 - else, `throw new TypeError`

>Register with children that does not extends the parent
Nice case, I think we should add a typeguard implementation that checks inheritance over children and throw an error if a "non-extending-parent child" is found.

>Register with the parent among the children
To me, you can't be the child of yourself, that's the same thing for OOP.

>Inheritance with explicit matching for the parent itself (same as above?)
We should add an optional parent field value in `Registration`. This approach would be way better than the previous one I think, because we don't break OOP laws.

>Inheritance with implicit matching for the parent itself (allowSelf?)
allowSelf should act as a fallback flag to me, meaning that if you don't have a child for the current value, you get the parent, but you have to explicitly set the flag if you want this behavior, else you get an error.

>Recursive inheritance, with multiple levels, like grandchildren and further
We already have a recursive approach in the current impl (see recursive-impl branch) and I think this is how we should do it. Because if you have a 10-levels deep inheritance, we have to use recursivity to find which child you're using.

BUT, each level has to add its own discriminator, else we can't know if it's just a child of parent, or a grandchild, etc. see https://github.com/kaiu-io/serializer/blob/recursive-impl/src/serializer.ts#L141

**Comment by noemi-salaun** [comment]
> Object without its discriminator field

I'm agree

> Object with unmatching discriminator value

I think if the parent isn't explicitly asked (allowSelf + null value) we shouldn't fallback to the parent by default. So for this case, throw for any unmatching discriminator.

> Register with children that does not extends the parent

I'm agree

> Register with the parent among the children

We should design the extends test needed for the case above, in a maner that the parent itself doesn't pass the test.

> Inheritance with explicit matching for the parent itself (same as above?)

Same case that previous.

> Inheritance with implicit matching for the parent itself (allowSelf?)

Already cover by allowSelf + null value.

> Recursive inheritance, with multiple levels, like grandchildren and further

I'm ok with it, I was just trying to list all the cases, not only the remanining.

**Comment by Supamiu** [comment]
Closed by #7.
